export const assignments = [
  {
    id: '0c7875c4-8814-481f-a237-7b14f83d6433',
    number: '27617.30.001',
    boards: [
      {
        serialNumber: 'D500-0157_AC_27617-00248',
        timestamp: '62678980',
        tester: 465,
        result: false,
        testProtocol: {
          activeDisplay: true,
          lightsUpLED: true,
          alarmSequence: true,
          voltageValue: 12074,
          temperature: 40,
          functionKeyboard: true,
          rotateShaft: true,
          hallSensors: true,
          individualPhases: true,
          switchCommutation: true,
          increaseSpeedEngine: true,
        },
      },
      {
        serialNumber: 'D500-0157_AC_27617-00249',
        timestamp: '62678980',
        tester: 465,
        result: true,
        testProtocol: {
          activeDisplay: true,
          lightsUpLED: true,
          alarmSequence: true,
          voltageValue: 12074,
          temperature: 30,
          functionKeyboard: true,
          rotateShaft: true,
          hallSensors: true,
          individualPhases: true,
          switchCommutation: true,
          increaseSpeedEngine: true,
        },
      },
    ],
  },
  {
    id: 'cc4157ce-56ca-46a8-b804-0b6c2a5c36f9',
    number: '27618.30.002',
    boards: [
      {
        serialNumber: 'D500-0157_AC_27618-00248',
        timestamp: '1623929430931',
        tester: 465,
        result: false,
        testProtocol: {
          activeDisplay: true,
          lightsUpLED: true,
          alarmSequence: true,
          voltageValue: 12074,
          temperature: 40,
          functionKeyboard: true,
          rotateShaft: true,
          hallSensors: true,
          individualPhases: true,
          switchCommutation: true,
          increaseSpeedEngine: true,
        },
      },
      {
        serialNumber: 'D500-0157_AC_27618-00249',
        timestamp: '1623929436195',
        tester: 465,
        result: true,
        testProtocol: {
          activeDisplay: true,
          lightsUpLED: true,
          alarmSequence: true,
          voltageValue: 12074,
          temperature: 30,
          functionKeyboard: true,
          rotateShaft: true,
          hallSensors: true,
          individualPhases: true,
          switchCommutation: true,
          increaseSpeedEngine: true,
        },
      },
    ],
  },
];
