export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const GET_ASSIGNMENT = 'GET_ASSIGNMENT';
export const GET_STORAGE_PATH = 'GET_STORAGE_PATH';
export const SET_STORAGE_PATH = 'SET_STORAGE_PATH';
export const CLEAR_ASSIGNMENT_SELECTED = 'CLEAR_ASSIGNMENT_SELECTED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const ADD_TESTED_BOARD_TO_ASSIGNMENT = 'ADD_TESTED_BOARD_TO_ASSIGNMENT';
export const ADD_NEW_TESTED_BOARD_TO_ASSIGNMENT =
  'ADD_NEW_TESTED_BOARD_TO_ASSIGNMENT';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
