export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const ASSIGNMENT_ERROR = 'ASSIGNMENT_ERROR';
export const ADD_TESTED_BOARD_TO_ASSIGNMENT = 'ADD_TESTED_BOARD_TO_ASSIGNMENT';
export const BOARD_ERROR = 'BOARD_ERROR';
